version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10. # Invoke the Heroku orb

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.15.2-jessie-browsers-legacy
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Show current directory
          command: pwd
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Linting
          command: npm run lint
      #      - run:
      #          name: Testing
      #          command: npm run test
      - run:
          name: Building
          command: npm run build:ssr
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
            - package.json
  heroku_deploy:
      jobs:
        - heroku/deploy-via-git

workflows:
  version: 2
  -deploy:
    jobs:
      - build
      - heroku_deploy:
          requires:
            - build
          filters:
            branches:
              only: master
